server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:/mydatabase
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:/db/migration
    out-of-order: false

security:
  jwt:
    token:
      secret-key: 8xATUx4r2L52
      expire-length: 604800000 #1 week