name: Code compilation and tests check.

# Whenever you request a Pull Request this action will be activated.
on: pull_request


jobs:

  # This action compile the project.
  compile:
    runs-on: ubuntu-latest
    name: Compile Spring Boot project
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: ./mvnw compile

  # This action run all project tests.
  tests:
    runs-on: ubuntu-latest
    name: Runing tests
    needs: [compile]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run unit tests
        run: ./mvnw test